config/routes.rb
Rails.application.routes.draw do
  root 'institutions#index'
  resources :categories, :institutions, :pictures, :reviews
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is_admin?
        can :manage, :all
    end

    if user.present?  
      can :read, Institution, user_id: user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :institutions
end

app/models/institution.rb
class Institution < ApplicationRecord
  belongs_to :category
  belongs_to :user

  has_many :pictures
  has_many :reviews
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :institution
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :institution
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

	has_many :reviews
	has_many :institutions
	has_many :pictures
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	rescue_from CanCan::AccessDenied do |exception|
		respond_to do |format|
			format.json { head :forbidden, content_type: 'text/html' }
			format.html { redirect_to root_url, notice: exception.message }
			format.js   { head :forbidden, content_type: 'text/html' }
		end
	end

	def access_denied(exception)
		flash[:danger] = exception.message
		redirect_to root_path
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
   
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy

    @category = Category.find(params[:id])
    @category.delete

    redirect_to categories_path
  
  end

  private
  def category_params
    params.require(:category).permit(:title)
  end

  
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  def index
  	@institutions = Institution.all
  end

  def new
  	@institution = Institution.new
  end

  def create
  	@institution = current_user.institutions.build(institution_params)
    if @institution.save
      redirect_to institutions_path
    else
      render 'edit'
    end
  end

  def destroy

    @institution = Institution.find(params[:id])
    @institution.delete

    redirect_to institutions_path
  
  end

  private

  def institution_params
    params.require(:institution).permit(:title, :description, :category_id, :user_id)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def edit
  end

  def delete
  end

  def create
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def create
  end

  def delete
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoryes_helper.rb
module CategoryesHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
  <%= f.input :title %>
  <%= f.button :submit %>
<% end %>

app/views/categories/create.html.erb
<h1>Categoryes#create</h1>
<p>Find me in app/views/categoryes/create.html.erb</p>

app/views/categories/delete.html.erb
<h1>Categoryes#delete</h1>
<p>Find me in app/views/categoryes/delete.html.erb</p>

app/views/categories/index.html.erb
<%= link_to 'New category', new_category_path %>

<table>

  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
 
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.title %></td>
      <td>
        <%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<% @categories.each do |category| %>

    <tr>

      <td><%= category.title %></td>

      <td>

        <%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: 'Are you sure?'} %>

      </td>

    </tr>

  <% end %>

app/views/institutions/_form.html.erb
<%= simple_form_for @institution do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.association :category %>
  <%= f.button :submit %>
<% end %>

app/views/institutions/create.html.erb
<h1>Institutions#create</h1>
<p>Find me in app/views/institutions/create.html.erb</p>

app/views/institutions/edit.html.erb
<h1>Institutions#edit</h1>
<p>Find me in app/views/institutions/edit.html.erb</p>

app/views/institutions/index.html.erb
<%= link_to 'New Institution', new_institution_path %>

<table>

	<tr>
		<th>Name</th>
		<th>Actions</th>
	</tr>

	<% @institutions.each do |institution| %>
	<tr>
		<td><%= institution.title %></td>
		
		<td>
			<%= link_to 'Delete', institution_path(institution), method: :delete, data: {confirm: 'Are you sure?'} %>
		</td>
	</tr>
	<% end %>
</table>

app/views/institutions/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Places</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        &#x2630;
      </button>

      <%= link_to 'All institutions', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%= link_to 'Categories', categories_path, class: 'navbar-brand' %>
        </li>
        
        
        <ul class="nav navbar-nav">
          <%= link_to 'Reviews', reviews_path, class: 'navbar-brand' %>
        </li>
      </ul>
    </div>
    <div class="navbar-nav ml-auto">
      <div>
       <%= link_to 'Sign in', new_user_session_path, class: 'navbar-brand' %>
     </div>
     <% if user_signed_in? %>
     <div class="nav-item">
      <span class="navbar-text">
        Hello, &nbsp;
      </span>
    </div>
  </div>


  <div class="dropdown show">
    <%= link_to current_user.email, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
    </div>
    <div>
      <% end %>
    </div>
  </div>
</div>
</div>

</nav>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/delete.html.erb
<h1>Pictures#delete</h1>
<p>Find me in app/views/pictures/delete.html.erb</p>

app/views/pictures/edit.html.erb
<h1>Pictures#edit</h1>
<p>Find me in app/views/pictures/edit.html.erb</p>

app/views/pictures/index.html.erb
<h1>Pictures#index</h1>
<p>Find me in app/views/pictures/index.html.erb</p>

app/views/pictures/new.html.erb
<h1>Pictures#new</h1>
<p>Find me in app/views/pictures/new.html.erb</p>

app/views/pictures/show.html.erb
<h1>Pictures#show</h1>
<p>Find me in app/views/pictures/show.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/delete.html.erb
<h1>Reviews#delete</h1>
<p>Find me in app/views/reviews/delete.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>